version: '3'

networks: 
    laravel:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx-batata
        ports: 
            - "8080:80"
        volumes: 
            - ./src:/var/www/html
            -  :/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - mysql
        networks: 
            - laravel

     
    mysql:
        image: mysql:5.7.22
        container_name: mysql-batata
        restart: unless-stopped
        tty: true
        ports: [4306:3306]
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: adsblog
            MYSQL_USER: root
            MYSQL_PASSWORD: root@123
            MYSQL_ROOT_PASSWORD: root@123
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - laravel
     
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes: 
            - ./src:/var/www/html
        ports: [9000:9000]
        networks: 
            - laravel